baseURL = "https://sessiond.org/"
languageCode = "en-us"
title = "sessiond"
theme = "geekdoc"

pluralizeListTitles = false
enableGitInfo = true

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

[markup.tableOfContents]
startLevel = 2
endLevel = 4

[params]
geekdocLogo = "favicon/favicon.ico"
geekdocMenuBundle = true
geekdocNextPrev = false
geekdocSearch = false
geekdocBreadcrumb = false
geekdocRepo="https://github.com/jcrd/sessiond.org"

[minify]
disableHTML = true
